### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by v0ldemar01** [v0ldemar01/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо

**Comment by volodymyr-minchenko** [comment]
― I`ve come close to death too many times and I`ve even died and come back to life. I have a close connection to animals, espacially direwolves and dragons. I`m a compassionate and loyal man, just ask my family.
People used to call me a bastard, but now - The Targaryen Wolf.

**Comment by volodymyr-minchenko** [comment]
― I\`ve come close to death too many times and I\`ve even died and come back to life. I have a close connection to animals, espacially direwolves and dragons. I`m a compassionate and loyal man, just ask my family.
People used to call me a bastard, but now - The Targaryen Wolf.

**Comment by volodymyr-minchenko** [comment]
<h2>RÉSUMÉ</h2>
<p>&mdash; I`ve come close to death too many times and I`ve even died and come back to life. I have a close connection to animals, espacially direwolves and dragons. I`m a compassionate and loyal man, just ask my family.
People used to call me a bastard, but now - The Targaryen Wolf. </p>
