### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by v0ldemar01** [v0ldemar01/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці

**Comment by volodymyr-minchenko** [comment]
<h3>Languages</h3>

```
<section>
  <h3>Languages</h3>
  <p class="tags small"><span>Dothraki </span><span>Valyrian </span><span>Common</span></p>
</section>
```

**Comment by volodymyr-minchenko** [comment]
<h3>Skills and interests</h3>

```
<section>
  <p><strong>Weapon: </strong>Longclaw-Valyrian Steel Blade</p>
  <p><strong>Pets: </strong>Ghost(Direwolf)</p>
  <p><strong>Supernatural: </strong>Can Rise From the Dead</p>
</section>
```

**Comment by volodymyr-minchenko** [comment]
<h3>Strengths</h3>

```
<section>
  <ul>
    <li>Self-resurrection and recovery</li>
    <li>Army and battle-force acquisition</li>
    <li>Diplomacy/gaining trust of allies</li>
    <li>Deconstructing/evaluating war strategies</li>
</ul>  
</section>
```

**Comment by volodymyr-minchenko** [comment]
<h3>Accomplishments</h3>

```
<section>
  <ul>
    <li>Killed a While Walker (just as shocked as you)</li>
    <li>Rose from the dead (we will see how it pans out)</li>
    <li>998<sup><small>th</small></sup>  Lord Commander</li>
    <li>Cared for and raised a wolf (fed, castle trained, etc.)</li>
</ul>  
</section>
```

**Comment by volodymyr-minchenko** [comment]
<h3>Education</h3>
<section>
 <i><h5>Winterfell | 285 AL - 298 Al</h5></i> 
 <h4>Student of Maester Luwin & Ser Rodrick Cassel </h4>
  <ul>
    <li>Trained in various arms including bow and arrow, longsword, and close combat</li>
    <li>Received a Highborn education studing statecraft, oration, military strategy, and Westerosi History</li>    
</ul>  
</section>

**Comment by volodymyr-minchenko** [comment]
<h3>Gifs</h3>
<section>
 <img src="https://media0.giphy.com/media/3og0IHyZMxZNkNOWT6/200w.webp?cid=ecf05e47cku7canerlhbgupfpbebzn1qpo1xdso7efsin85y&rid=200w.webp" class="gif">
            <img src="https://media0.giphy.com/media/39yFzWEcidBLFM5iFf/200w.webp?cid=ecf05e47lptqi3iam16blvpwl5h4mn2enzbq3aqbm6llxorc&rid=200w.webp" class="gif">
            <img src="https://media0.giphy.com/media/3og0IH6dEW7dsQ42Q0/200w.webp?cid=ecf05e47osbv3ca6gqmzcu7jibm424anl2ap60x20vwlcueh&rid=200w.webp" class="gif"> 
            <img src="https://media4.giphy.com/media/lPd2V3kG7gaGU2gEIC/200w.webp?cid=ecf05e47t3tauxa9frhp0b7iscezxd76l7m3h2y56m7i48aw&rid=200w.webp" class="gif"> 
</section>

**Comment by v0ldemar01** [comment]
Thanks)))))
